name: Deploy and Test

on:
  push:
    branches:
      - main
      - preview/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to Vercel
        id: deploy
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            vercel --token ${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Get Deployment URL
        id: get-url
        run: echo "VERCEL_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }} --output=json | jq -r '.url')" >> $GITHUB_ENV

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run E2E Tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.VERCEL_URL }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}