name: E2E Tests

on:
  workflow_dispatch:
  deployment_status:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Update lockfile
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git checkout -b temp-branch-${{ github.run_id }}
          pnpm install --no-frozen-lockfile
          git add pnpm-lock.yaml
          git commit -m "Update pnpm-lock.yaml" || echo "No changes to commit"
          git push origin temp-branch-${{ github.run_id }}

  run-e2e-tests:
    needs: update-lockfile
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch and checkout temp branch
        run: |
          git fetch origin
          git checkout temp-branch-${{ github.run_id }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright dependencies
        run: pnpm exec playwright install chromium

      - name: Set deployment URL
        run: |
          echo "DEPLOYMENT_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV

      - name: Verify deployment
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.DEPLOYMENT_URL }}")
          echo "Deployment URL HTTP status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "Deployment verified successfully"
          else
            echo "Warning: Deployment verification failed. Proceeding with tests anyway."
          fi

      - name: Run Playwright E2E Tests
        run: pnpm run test:e2e
        env:
          DEPLOYMENT_URL: ${{ env.DEPLOYMENT_URL }}
          E2E_CLERK_USER_USERNAME: ${{ secrets.E2E_CLERK_USER_USERNAME }}
          E2E_CLERK_USER_PASSWORD: ${{ secrets.E2E_CLERK_USER_PASSWORD }}
          CI: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Clean up temp branch
        if: always()
        run: |
          git push origin --delete temp-branch-${{ github.run_id }}
