name: E2E Tests

on:
  workflow_dispatch:
  deployment_status:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Update lockfile
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b temp-branch
          pnpm install --no-frozen-lockfile
          git add pnpm-lock.yaml
          git commit -m "Update pnpm-lock.yaml" || echo "No changes to commit"
          git push origin temp-branch:${{ github.ref }} -f

  run-e2e-tests:
    needs: update-lockfile
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright dependencies
        run: pnpm exec playwright install chromium

      - name: Wait for preview deployment
        run: |
          echo "Waiting for preview deployment to be ready..."
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w "%{http_code}" "${{ github.event.deployment_status.target_url }}")" != "200" ]]; do sleep 5; done'
          echo "Preview deployment is ready!"

      - name: Run Playwright E2E Tests
        run: pnpm run test:e2e
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          E2E_CLERK_USER_USERNAME: ${{ secrets.E2E_CLERK_USER_USERNAME }}
          E2E_CLERK_USER_PASSWORD: ${{ secrets.E2E_CLERK_USER_PASSWORD }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
