name: E2E Tests

on:
  workflow_dispatch:
  deployment_status:

jobs:
  run-e2e-tests:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright dependencies
        run: pnpm exec playwright install chromium

      - name: Set deployment URL
        run: |
          echo "DEPLOYMENT_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV

      - name: Verify deployment
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.DEPLOYMENT_URL }}")
          echo "Deployment URL HTTP status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "Deployment verified successfully"
          else
            echo "Warning: Deployment verification failed. Proceeding with tests anyway."
          fi

      - name: Run Playwright E2E Tests
        run: pnpm run test:e2e
        env:
          DEPLOYMENT_URL: ${{ env.DEPLOYMENT_URL }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          CI: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
