name: Playwright Tests

on:
  push:
    branches: 
      - main
      - development  # Add any other branches you want to trigger tests on
  pull_request:
    branches: 
      - main
      - development

jobs:
  run-e2es:  # Job name for end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci  # Using npm ci for clean installs
      - name: Install Playwright browsers
        run: npx playwright install --with-deps  # Install Playwright browsers
      - name: Set BASE_URL
        run: echo "BASE_URL=https://the-front-1.vercel.app" >> $GITHUB_ENV  # Set BASE_URL based on branch
      - name: Set Bypass Token
        run: echo "BYPASS_TOKEN=${{ secrets.BYPASS_TOKEN }}" >> $GITHUB_ENV  # Set Bypass Token from GitHub Secrets
      - name: Run tests
        run: npx playwright test  # Execute Playwright tests